### ISSUE TITLE
Back Button is not functioning

### ISSUE THREAD

**Issue by ihsan314** [yuntaowu2000/CPEN321-Quizzical#8]
Normally Android apps do powerful things with the system back button. These normally center around switching to the previous view while preserving state appropriately. From experimentation it is clear our app is not held to this standard.

Let's allow the back button to be a means of safely traversing views within the app, and have Expresso tests to verify this.

**Comment by ihsan314** [comment]
From the various activities (InitiActivity, PictureActivity) the back button should save the state of these activities and return to the HomeActivity. Within the QuizActivity the back button should be a no-op.

**Comment by yuntaowu2000** [comment]
Fixed
