### ISSUE TITLE
Travis CI json file

### ISSUE THREAD

**Issue by ihsan314** [yuntaowu2000/CPEN321-Quizzical#9]
In order for Travis CI to be able to run our code properly, we need to have our Firebase token file. We can't directly commit it, but following the TA's steps below, we should be able to get it onto Travis CI:

> Hi, I believe you are asking how to securely pass a file with secrets to Travis CI, please correct me if I misunderstood. You can use the Encrypting Files feature of Travis CI. Basically you should (1) encrypt your secret file using Travis CI cli (2) commit and push the encrypted secret file (3) add a decryption step to your travis.yml file. Here is the detailed guide: https://docs.travis-ci.com/user/encrypting-files/
> 
> Apart from encrypting the entire file(s), Travis CI also supports environment variables encryption, which can be used to secure single secret such as your API key or credential. The high level steps are to: (1) store the secret as an environment variable (2) use Travis CI cli to generate an encrypted environment variable (3) add the encrypted environment variable to your .travis.yml file. Here is the detailed guide: https://docs.travis-ci.com/user/environment-variables/
>
> Here are more references to how to secure your data on Travis CI:
>
> - https://docs.travis-ci.com/user/best-practices-security/
>
> - https://stackoverflow.com/questions/9338428/using-secret-api-keys-on-travis-ci

**Comment by yuntaowu2000** [comment]
encoded file now on GitHub, need to check if it works

**Comment by ihsan314** [comment]
In [line 210](https://travis-ci.com/github/yuntaowu2000/CPEN321-Quizzical/builds/201788330#L210) of the build it appears the decryption fails. The following line states `iv undefined`. Looking around, it seems the environment variables may not be populated correctly:
- https://github.com/travis-ci/travis-ci/issues/9451
- https://travis-ci.community/t/iv-undefined-in-openssl-invocation/6614/3
- https://github.com/travis-ci/travis-ci/issues/9668
